language: node_js
node_js:
    - "7"
branches:
    only:
        - master
before_script:
    - npm install -g firebase-tools
script:
    - echo "deploying"
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: false
  token:
    secure: "oGl2QSw853y5WR8sxRjIRvfTtFieRXVEWf6PtAOjpeH0lpAuHWN8u00AkVDAAPA1jeg1Zy5XX1flGgjivdJQzSHY3v/iSMfvhGUCvvVYulx0uLOElgKZ07qn0VevZ3o886hV3KLpYeWLM5NfpFw1Sd2k4ufpPSr+VqJOAnnPp7r7bt5xvDb+1mJ1It/Rkt0x8FDA2lhFjBrfYjWSWXNouuUeDkQWU/K9p4TpD3MAiarZEc+8yprblJrFFT7rb95MjXydoPPyl/ixmFCTrOmNR02hDZctx6jzRMohrJuqL5bEWyVwzL0q5dnu6l73sAnAJl6fyHFvgDEx4RPYPSOTsXIkdEq/36JL+BGT8GvZc3C1CG4ci1R8aZiRr5Dj7eowW4OV0Fi062kC9jPsEecaRBXQMucHLbSaJ2S/mQ0h1gh1Itv1/8e9rdnDQ2rdSJJRcQLnYNhp+7Oh6slT+4v/hGMkc/z5nth+JcLu7pxyaiaG6JLmHaTbBHh0JX4ylQr1fTzvtKV18hrbvHQ8jigGCal5eh/D0A9LWzwww/j81b6JsFOg8fAGHYF1E9APMEyV1J6io6DrFTg7dO+X5IWknr3Roro+ehWmszyCGDan5YAygZE7enjHzIPfBTs/OcWIy7OqcudgbxJzKAYxWgKI5yEL2kEkRgJApA6rL+107s0="
  project: "sohan-site"
